[2024-10-08T22:04:41.334+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-08T22:04:41.390+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbyte_sync_tables_postgres.airbyte_check_sync scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-08T22:04:41.429+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbyte_sync_tables_postgres.airbyte_check_sync scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-08T22:04:41.431+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-08T22:04:41.486+0000] {taskinstance.py:2330} INFO - Executing <Task(AirbyteJobSensor): airbyte_check_sync> on 2024-10-07 00:00:00+00:00
[2024-10-08T22:04:41.510+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'airbyte_sync_tables_postgres', 'airbyte_check_sync', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/airbyte_sync_tables_postgres.py', '--cfg-path', '/tmp/tmppsb2gqvm']
[2024-10-08T22:04:41.517+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask airbyte_check_sync
[2024-10-08T22:04:41.524+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=206) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-08T22:04:41.527+0000] {standard_task_runner.py:64} INFO - Started process 207 to run task
[2024-10-08T22:04:41.660+0000] {task_command.py:426} INFO - Running <TaskInstance: airbyte_sync_tables_postgres.airbyte_check_sync scheduled__2024-10-07T00:00:00+00:00 [running]> on host 60eb82c11812
[2024-10-08T22:04:42.009+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vizentec-engdados' AIRFLOW_CTX_DAG_ID='airbyte_sync_tables_postgres' AIRFLOW_CTX_TASK_ID='airbyte_check_sync' AIRFLOW_CTX_EXECUTION_DATE='2024-10-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-07T00:00:00+00:00'
[2024-10-08T22:04:42.013+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-08T22:04:42.095+0000] {baseoperator.py:400} WARNING - AirbyteJobSensor.execute cannot be called outside TaskInstance!
[2024-10-08T22:04:42.122+0000] {base.py:84} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-10-08T22:04:42.266+0000] {airbyte.py:113} INFO - Waiting for job 18 to complete.
[2024-10-08T22:05:42.296+0000] {base.py:84} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-10-08T22:05:42.479+0000] {airbyte.py:113} INFO - Waiting for job 18 to complete.
[2024-10-08T22:06:42.519+0000] {base.py:84} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-10-08T22:06:43.446+0000] {airbyte.py:108} INFO - Job 18 completed successfully.
[2024-10-08T22:06:43.466+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-10-08T22:06:43.488+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-08T22:06:43.628+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=airbyte_sync_tables_postgres, task_id=airbyte_check_sync, run_id=scheduled__2024-10-07T00:00:00+00:00, execution_date=20241007T000000, start_date=20241008T220441, end_date=20241008T220643
[2024-10-08T22:06:43.946+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-10-08T22:06:44.075+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-08T22:06:44.078+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
